CREATE DATABASE IF NOT EXISTS pingdb;
CREATE DATABASE IF NOT EXISTS domaindb;

USE pingdb;

CREATE TABLE IF NOT EXISTS pingresult (
    id INT AUTO_INCREMENT PRIMARY KEY,
    host VARCHAR(255) NOT NULL,
    ping FLOAT NULL,
    ttl INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

USE domaindb;

CREATE TABLE IF NOT EXISTS domaincheck (
    id INT AUTO_INCREMENT PRIMARY KEY,
    domain VARCHAR(255) NOT NULL,
    curl_result TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);